FROM ghcr.io/dirtymieng/bootc-base:latest

# SELinux support for k3s
RUN dnf install -y container-selinux && \
    dnf install -y https://rpm.rancher.io/k3s/stable/common/centos/8/noarch/k3s-selinux-1.6-1.el8.noarch.rpm && \
    dnf clean all

# K3s lightweight Kubernetes (without default CNI - we'll use Cilium)
RUN curl -sfL https://get.k3s.io | \
    INSTALL_K3S_SKIP_START=true \
    INSTALL_K3S_SKIP_ENABLE=true \
    INSTALL_K3S_SKIP_SELINUX_RPM=true \
    INSTALL_K3S_SELINUX_WARN=true \
    INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy --disable=traefik" \
    sh -

# Cilium CLI
RUN CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt) && \
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-amd64.tar.gz && \
    tar xzvf cilium-linux-amd64.tar.gz -C /usr/local/bin && \
    rm cilium-linux-amd64.tar.gz

# Create CNI directory structure (mount point for tmpfs - see opt-cni-bin.mount)
RUN mkdir -p /opt/cni/bin

# Set KUBECONFIG for user
RUN echo 'export KUBECONFIG=~/.kube/config' >> /home/dirtymieng/.bashrc

# k3s not auto-enabled - start manually, then install Cilium:
# sudo systemctl enable --now k3s
# cilium install
