FROM ghcr.io/dirtymieng/bootc-base:latest

# K3s lightweight Kubernetes (without default CNI - we'll use Cilium)
RUN curl -sfL https://get.k3s.io | \
    INSTALL_K3S_SKIP_START=true \
    INSTALL_K3S_SKIP_ENABLE=true \
    INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy" \
    sh -

# Cilium CLI
RUN CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt) && \
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-amd64.tar.gz && \
    tar xzvf cilium-linux-amd64.tar.gz -C /usr/local/bin && \
    rm cilium-linux-amd64.tar.gz

# Container tools
RUN dnf install -y \
    podman \
    && dnf clean all

# k3s not auto-enabled - start manually, then install Cilium:
# sudo systemctl enable --now k3s
# cilium install
